import {GpuRuntime} from '../vendor/cuda-webshader/runtime/runtime.js';
const $=id=>document.getElementById(id),canvas=$('render'),reference=$('reference');
const defaults={depth:.55,wave:.55,caustic:1.25,tint:.8,exposure:.65,height:.9,pitch:-.27,fov:58};
const state={...defaults,stonework:1,wall:1,pavilion:1,time:5,playing:false},diag=window.studyDiagnostics={ready:false,errors:[],frames:0,state};
const ids=Object.keys(defaults);let rt,pixels,stride,width,height,busy=false;
function controls(){$('pavilion').checked=!!state.pavilion;$('wall').checked=!!state.wall;$('stonework').checked=!!state.stonework;for(const id of ids){$(id).value=state[id];$(id+'Value').textContent=state[id].toFixed(id==='fov'?1:2);}$('pause').textContent=state.playing?'Pause':'Resume';}
for(const id of ids)$(id).oninput=()=>{state[id]=+$(id).value;controls();};
$('pause').onclick=()=>{state.playing=!state.playing;controls();};$('reset').onclick=()=>{Object.assign(state,defaults,{time:5,playing:false,stonework:1,wall:1,pavilion:1});controls();compare();};
function compare(){const mode=$('mode').value;reference.style.opacity=mode==='render'?'0':mode==='overlay'?$('opacity').value:'1';reference.style.mixBlendMode=mode==='difference'?'difference':'normal';reference.style.clipPath=mode==='wipe'?`inset(0 ${100-+$('wipe').value}% 0 0)`:'none';$('divider').style.display=mode==='wipe'?'block':'none';$('divider').style.left=$('wipe').value+'%';$('opacityValue').textContent=Math.round(+$('opacity').value*100)+'%';$('caption').textContent={render:state.pavilion?'CUDA RENDER · LEFT PAVILION':state.wall?'CUDA RENDER · MOON-GATE WALL':state.stonework?'CUDA RENDER · WATER + STONEWORK':'CUDA RENDER · WATER ONLY',reference:'GENERATED REFERENCE',overlay:'REFERENCE OVER CUDA RENDER',wipe:'REFERENCE ← | → CUDA RENDER',difference:'ABSOLUTE RGB DIFFERENCE · BLACK = MATCH'}[mode];}
for(const id of ['mode','opacity','wipe'])$(id).oninput=compare;
$('save').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({reference:'jiangnan-pond-concept-v1.png',projection:'architectural-off-axis-v1',width,height,...state},null,2)],{type:'application/json'}));a.download='water-study-settings.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('zoom').onclick=()=>{const zoom=document.body.classList.toggle('nativePixels');$('zoom').textContent=zoom?'Fit comparison to window':'Inspect at 1:1 pixels';};
$('stonework').onchange=()=>{state.stonework=$('stonework').checked?1:0;compare();};
$('wall').onchange=()=>{state.wall=$('wall').checked?1:0;compare();};
$('pavilion').onchange=()=>{state.pavilion=$('pavilion').checked?1:0;compare();};
controls();compare();
function fail(e){diag.errors.push(String(e.message||e));$('error').hidden=false;$('error').textContent=diag.errors.join('\n');$('status').textContent='ERROR';console.error(e);}
try{
await reference.decode();width=reference.naturalWidth;height=reference.naturalHeight;stride=Math.ceil(width/64)*64;
canvas.width=width;canvas.height=height;$('stage').style.aspectRatio=`${width}/${height}`;$('resolution').textContent=`${width} × ${height} / NATIVE GRID`;
rt=await GpuRuntime.create({onError:fail});const source=(await Promise.all(['../src/clearwater.cu','./study.cu'].map(p=>fetch(p).then(r=>{if(!r.ok)throw Error(p);return r.text();})))).join('\n');
const k={};for(const entry of ['seed_spectrum','spectrum_rows','spectrum_norm','weather_update','evolve_spectrum','fft_pass','resolve_surface','clear_caustics','study_caustics','filter_caustics','study_render','study_present'])k[entry]=await rt.kernel(source,{entry,workgroupSize:['spectrum_rows','spectrum_norm'].includes(entry)?[64,1,1]:[8,8,1]});
const b=n=>rt.createBuffer(n),seed=b(3*65536*8),rows=b(768*4),scales=b(12),weather=b(32),spectralEnergy=rt.createBuffer(new Float32Array(3*65536).fill(1)),fft=[b(3*65536*16),b(3*65536*16)],surface=b(3*65536*16),photons=b(512*512*12),caustics=b(512*512*16),hdr=b(width*height*16);pixels=b(stride*height*4);
const WG=[32,32,3],grid=[Math.ceil(width/8),Math.ceil(height/8),1];
rt.batch().dispatch(k.seed_spectrum.bind({seed},{seedValue:7}),WG).dispatch(k.spectrum_rows.bind({seed,rows}),[12,1,1]).dispatch(k.spectrum_norm.bind({rows,scales}),[1,1,1]).dispatch(k.weather_update.bind({weather},{age:-1,direction:.64,strength:0,wind:3,rain:0,clouds:.12,dt:100,camX:0,camZ:0}),[1,1,1]).submit();await rt.idle();
const ctx=canvas.getContext('webgpu');ctx.configure({device:rt.device,format:'rgba8unorm',alphaMode:'opaque',usage:GPUTextureUsage.COPY_DST|GPUTextureUsage.RENDER_ATTACHMENT});let last=0;
async function frame(now){try{if(busy){requestAnimationFrame(frame);return;}busy=true;const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(state.playing)state.time+=dt;
const batch=rt.batch();batch.dispatch(k.evolve_spectrum.bind({seed,scales,output:fft[0],weather,spectralEnergy},{time:state.time,sea:1,depth:state.depth,weatherDt:0}),WG);
let src=0;for(let axis=0;axis<2;axis++)for(let p=1;p<256;p*=2){batch.dispatch(k.fft_pass.bind({input:fft[src],output:fft[1-src]},{p,axis,sign:1}),WG);src=1-src;}
batch.dispatch(k.resolve_surface.bind({input:fft[src],surface}),WG).dispatch(k.clear_caustics.bind({photons}),[64,64,1]).dispatch(k.study_caustics.bind({surface,photons},{depth:state.depth,wave:state.wave,time:state.time}),[128,128,1]).dispatch(k.filter_caustics.bind({photons,caustics}),[64,64,1]).dispatch(k.study_render.bind({surface,caustics,hdr},{width,height,cameraHeight:state.height,pitch:state.pitch,fov:state.fov,depth:state.depth,wave:state.wave,caustic:state.caustic,tint:state.tint,time:state.time,stonework:state.stonework,wall:state.wall,pavilion:state.pavilion}),grid).dispatch(k.study_present.bind({hdr,image:pixels},{width,height,stride,exposure:state.exposure}),grid).submit();
const enc=rt.device.createCommandEncoder();enc.copyBufferToTexture({buffer:pixels.gpuBuffer,bytesPerRow:stride*4,rowsPerImage:height},{texture:ctx.getCurrentTexture()},[width,height]);rt.device.queue.submit([enc.finish()]);await rt.idle();diag.ready=true;diag.frames++;diag.readbackBytes=rt.stats.readbackBytes;$('status').textContent=state.playing?'LIVE':`FIXED TIME / ${state.time.toFixed(2)} s`;busy=false;requestAnimationFrame(frame);
}catch(e){busy=false;fail(e);}}
async function measure(region=[.32,.7,.75,.95]){state.playing=false;controls();while(busy)await new Promise(r=>setTimeout(r,10));busy=true;try{await rt.idle();const packed=await rt.read(pixels,Uint32Array);const c=document.createElement('canvas');c.width=width;c.height=height;const two=c.getContext('2d',{willReadFrequently:true});two.drawImage(reference,0,0);const target=two.getImageData(0,0,width,height).data;let absolute=0,squares=0,count=0,checksum=2166136261;for(let y=Math.ceil(height*region[1]);y<Math.floor(height*region[3]);y++)for(let x=Math.ceil(width*region[0]);x<Math.floor(width*region[2]);x++){let p=packed[y*stride+x];checksum=Math.imul(checksum^p,16777619)>>>0;for(let channel=0;channel<3;channel++){const delta=((p>>>(channel*8))&255)-target[(y*width+x)*4+channel];absolute+=Math.abs(delta);squares+=delta*delta;count++;}}
const rowEdgesOpaque=Array.from({length:height},(_,y)=>(packed[y*stride]>>>24)===255&&(packed[y*stride+width-1]>>>24)===255).every(Boolean);
const result={checksum,rowEdgesOpaque,mae:absolute/count,rmse:Math.sqrt(squares/count),region,width,height,state:{...state}};diag.measurement=result;if(region[1]>.5)$('metric').textContent=`Foreground RGB error: MAE ${result.mae.toFixed(2)} / 255 · RMSE ${result.rmse.toFixed(2)} / 255. This measures the outlined water region only. A pixel-perfect match would be 0.`;return result;}finally{busy=false;}}
$('measure').onclick=()=>measure().catch(fail);
$('pavilionMeasure').onclick=()=>measure([0,0,.27,.39]).then(r=>{$('pavilionMetric').textContent=`Pavilion region MAE ${r.mae.toFixed(2)} / 255 · RMSE ${r.rmse.toFixed(2)} / 255`;}).catch(fail);
$('wallMeasure').onclick=()=>measure([.36,.015,.97,.34]).then(r=>{$('wallMetric').textContent=`Wall region MAE ${r.mae.toFixed(2)} / 255 · RMSE ${r.rmse.toFixed(2)} / 255`;}).catch(fail);
$('bridgeMeasure').onclick=()=>measure([.375,.285,.655,.44]).then(r=>{$('bridgeMetric').textContent=`Bridge region MAE ${r.mae.toFixed(2)} / 255 · RMSE ${r.rmse.toFixed(2)} / 255`;}).catch(fail);window.studyLab={state,measure};requestAnimationFrame(frame);
}catch(e){fail(e);}
