import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:false,args:['--enable-unsafe-webgpu']});
try {
 const page=await browser.newPage({viewport:{width:1720,height:1080}}),errors=[];
 page.on('pageerror',e=>errors.push(String(e)));
 page.on('response',r=>{if(r.status()>=400)errors.push(r.url());});
 await page.goto(process.env.STUDY_URL||'http://127.0.0.1:5186/study/');
 await page.waitForFunction(()=>window.studyDiagnostics?.ready||window.studyDiagnostics?.errors.length,{},{timeout:120000});
 assert.deepEqual(await page.evaluate(()=>studyDiagnostics.errors),[]);
 const frames=async()=>{const n=await page.evaluate(()=>studyDiagnostics.frames);await page.waitForFunction(n=>studyDiagnostics.frames>n+1,n);};
 await frames();assert.equal(await page.evaluate(()=>studyDiagnostics.readbackBytes),0);
 const geometry=await page.evaluate(()=>{const c=document.querySelector('canvas'),r=document.querySelector('#reference');return{canvas:[c.width,c.height],image:[r.naturalWidth,r.naturalHeight],c:c.getBoundingClientRect().toJSON(),r:r.getBoundingClientRect().toJSON()};});
 assert.deepEqual(geometry.canvas,[1672,941]);assert.deepEqual(geometry.image,geometry.canvas);assert.deepEqual(geometry.c,geometry.r);
 const first=await page.evaluate(()=>studyLab.measure());await frames();const repeated=await page.evaluate(()=>studyLab.measure());
 assert(first.rowEdgesOpaque,'Padded rows must preserve opaque pixels at both image edges');
 assert(Number.isFinite(first.mae)&&first.mae>0&&first.mae<255);assert(Math.abs(first.mae-repeated.mae)<.01,'Paused frames must be repeatable');
 const gateGeometry=await page.evaluate(async()=>{
  const {GpuRuntime}=await import(new URL('../vendor/cuda-webshader/runtime/runtime.js',location.href).href);
  const rt=await GpuRuntime.create();
  const source=(await Promise.all(['../src/clearwater.cu','./study.cu'].map(p=>fetch(p).then(r=>r.text())))).join('\n')+`
__global__ void gate_probe(float4 *result){result[0]=make_float4(studyWallTrace(v3(.97f,.40f,0),v3(0,0,-1),4),studyWallTrace(v3(1.5f,.40f,0),v3(0,0,-1),4),studyWallTrace(v3(.97f,.834f,0),v3(0,0,-1),4),1);
float3 o=v3(0,.9f,3.3f);
result[1]=make_float4(studyPavilionTrace(o,norm(sub(v3(-1.745f,.60f,-1.1f),o)),8),studyPavilionTrace(o,norm(sub(v3(-1.92f,.60f,-1.1f),o)),8),studyPavilionTrace(v3(-1.70f,.70f,-1.1f),v3(0,-1,0),2),studyPavilionTrace(v3(-1.6f,2,-.8f),v3(0,-1,0),3));
float3 d=norm(sub(v3(-2.20f,.65f,-.435f),o));float t=studyPavilionTrace(o,d,8);float3 p=add(o,mul(d,t));float2 hit=studyPavilionMap(p);float3 n=studyPavilionNormal(p);
result[2]=make_float4(p.z,hit.y,n.z,t);
}`;
  const kernel=await rt.kernel(source,{entry:'gate_probe',workgroupSize:[1,1,1]}),result=rt.createBuffer(48);
  rt.batch().dispatch(kernel.bind({result}),[1,1,1]).submit();await rt.idle();
  const values=Array.from(await rt.read(result,Float32Array));rt.destroyBuffer(result);rt.device.destroy();return values;
 });
 assert(gateGeometry[0]<0,'A ray through the gate must pass through the opening');
 assert(gateGeometry[1]>0&&gateGeometry[2]>0,'Plaster and stone surround must be solid geometry');
 assert(gateGeometry[4]>0,'Pavilion column must be solid');
 assert(gateGeometry[5]<0,'The open pavilion bay must not be a solid billboard');
 assert(gateGeometry[6]>0&&gateGeometry[7]>0,'Porch and roof must be solid geometry');
 assert(Math.abs(gateGeometry[8]+.435)<.002&&gateGeometry[9]===1&&gateGeometry[10]>.99,'The visible plaster front must be hit before entering its volume');
 const pavilion=await page.evaluate(()=>studyLab.measure([0,0,.27,.39]));
 const pavilionWater=await page.evaluate(()=>studyLab.measure([.06,.4,.25,.64]));
 await page.locator('#pavilion').uncheck();await frames();
 const noPavilion=await page.evaluate(()=>studyLab.measure([0,0,.27,.39]));
 const noPavilionWater=await page.evaluate(()=>studyLab.measure([.06,.4,.25,.64]));
 assert(pavilion.mae<noPavilion.mae,'Pavilion should improve the reference region');
 assert.notEqual(pavilionWater.checksum,noPavilionWater.checksum,'Pavilion must affect its water reflection');
 await page.locator('#pavilion').check();await frames();
 await page.locator('#components').evaluate(e=>e.open=true);
 const wall=await page.evaluate(()=>studyLab.measure([.36,.015,.97,.34]));
 const wallWater=await page.evaluate(()=>studyLab.measure([.65,.43,.9,.61]));
 await page.locator('#wall').uncheck();await frames();
 const noWall=await page.evaluate(()=>studyLab.measure([.36,.015,.97,.34]));
 const noWallWater=await page.evaluate(()=>studyLab.measure([.65,.43,.9,.61]));
 assert(wall.mae<noWall.mae,'Wall geometry should improve the reference region');
 assert.notEqual(wallWater.checksum,noWallWater.checksum,'Wall must appear in water reflections');
 await page.locator('#wall').check();await frames();
 const bridge=await page.evaluate(()=>studyLab.measure([.375,.285,.655,.44]));
 const reflected=await page.evaluate(()=>studyLab.measure([.38,.45,.65,.64]));
 await page.locator('#stonework').uncheck();await frames();const absent=await page.evaluate(()=>studyLab.measure([.375,.285,.655,.44]));
 const noReflection=await page.evaluate(()=>studyLab.measure([.38,.45,.65,.64]));assert.notEqual(reflected.checksum,noReflection.checksum,'Stonework must affect the water below the bridge');
 assert(bridge.mae<absent.mae,'Stonework should improve the bridge region over absent geometry');
 await page.locator('#stonework').check();await frames();
 await page.click('#bridgeMeasure');await page.waitForFunction(()=>document.querySelector('#bridgeMetric').textContent.includes('MAE'));
 await page.locator('#components').evaluate(e=>e.open=false);
 await page.screenshot({path:'previews/study-overlay.png'});
 await page.selectOption('#mode','render');assert.equal(await page.locator('#reference').evaluate(e=>e.style.opacity),'0');
 await page.screenshot({path:'previews/study-render.png'});
 await page.selectOption('#mode','difference');assert.equal(await page.locator('#reference').evaluate(e=>e.style.mixBlendMode),'difference');await page.screenshot({path:'previews/study-difference.png'});
 await page.selectOption('#mode','wipe');await page.locator('#wipe').fill('37');assert.equal(await page.locator('#reference').evaluate(e=>e.style.clipPath),'inset(0px 63% 0px 0px)');
 await page.click('#zoom');assert.equal(await page.locator('canvas').evaluate(e=>e.getBoundingClientRect().width),1672);await page.click('#zoom');
 await page.locator('#lighting').evaluate(e=>e.open=true);
 await page.locator('#exposure').fill('0.25');await frames();const changed=await page.evaluate(()=>studyLab.measure());assert(Math.abs(changed.mae-first.mae)>5,'Exposure control must affect the GPU output');
 await page.click('#reset');await page.click('#pause');await frames();assert(await page.evaluate(()=>studyLab.state.time>5));await page.click('#pause');const time=await page.evaluate(()=>studyLab.state.time);await frames();assert.equal(await page.evaluate(()=>studyLab.state.time),time);
 await page.click('#reset');await frames();assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>studyDiagnostics.errors),[]);
 const report={url:page.url(),geometry,gateGeometry,pavilion,noPavilion,pavilionWater,noPavilionWater,first,repeated,wall,noWall,wallWater,noWallWater,bridge,absent,reflected,noReflection,changed,errors};await writeFile('previews/study-verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify({pavilion:pavilion.mae,withoutPavilion:noPavilion.mae,mae:first.mae,rmse:first.rmse,wall:wall.mae,withoutWall:noWall.mae,bridge:bridge.mae,withoutBridge:absent.mae,errors,normalReadbackBytes:0}));
} finally {await browser.close();}
